development:
  adapter: postgresql
  encoding: unicode
  database: instagator_landing
  host: localhost
  username: instagator_landing
  password: 
test:
  adapter: postgresql
  encoding: unicode
  database: instagator_landing_test
  host: localhost
  pool: 5
  username: instagator_landing
  password:
production:
  adapter: postgresql
  encoding: unicode
  database: instagator_landing_production
  pool: 25
  username: instagator_landing
  password: